import { predictBudgetShiftOutcome } from './budgetModel';

export function buildGazetteDocument({ advisorMessages = [], leaderboard = [], scenario = {} }) {
  const pred = predictBudgetShiftOutcome({
    healthcarePct: scenario.healthcarePct ?? 10,
    educationPct: scenario.educationPct ?? 5,
    infrastructurePct: scenario.infrastructurePct ?? -8,
    industrialPct: scenario.industrialPct ?? 0,
  });

  const issued = new Date().toISOString();

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Aegis Fiscal — Proposed Budget Gazette (Cabinet Draft)</title>
  <style>
    body { font-family: 'Times New Roman', Times, serif; max-width: 720px; margin: 48px auto; color: #111; line-height: 1.45; }
    h1 { font-size: 22px; letter-spacing: 0.04em; border-bottom: 2px solid #0f2b5b; padding-bottom: 8px; }
    h2 { font-size: 15px; margin-top: 28px; color: #0f2b5b; }
    .meta { font-size: 12px; color: #444; margin-bottom: 24px; }
    .seal { text-align: center; font-size: 11px; letter-spacing: 0.2em; text-transform: uppercase; margin-bottom: 16px; color: #c39c5b; }
    table { width: 100%; border-collapse: collapse; font-size: 13px; margin-top: 8px; }
    th, td { border: 1px solid #ccc; padding: 8px; text-align: left; }
    th { background: #f4f6fa; }
    .footnote { font-size: 11px; color: #555; margin-top: 32px; }
  </style>
</head>
<body>
  <div class="seal">Aegis Fiscal · Statecraft & Governance Suite</div>
  <h1>Proposed Budget Allocation — Cabinet Review Gazette (Draft)</h1>
  <div class="meta">Issued (UTC): ${issued}<br/>Classification: Official — Preliminary · Not legally binding</div>

  <h2>I. Executive summary</h2>
  <p>This draft consolidates AI-assisted simulations, inter-region efficiency signals, and cultural–geographic safeguards into a single cabinet-ready record. All figures are illustrative pending reconciliation with OpenBudgetsIndia and World Bank master tables.</p>

  <h2>II. ML outcome projection (Random Forest ensemble)</h2>
  <table>
    <tr><th>Metric</th><th>Value</th></tr>
    <tr><td>Ensemble mean (normalized welfare uplift)</td><td>${pred.ensembleMean}</td></tr>
    <tr><td>Projected life expectancy (synthetic index)</td><td>${pred.projectedLifeExpectancyYears} yrs</td></tr>
    <tr><td>Fiscal stress index (0–10)</td><td>${pred.fiscalStressIndex}</td></tr>
    <tr><td>Calibration</td><td>${pred.calibration}</td></tr>
  </table>

  <h2>III. Inter-region performance (excerpt)</h2>
  <table>
    <tr><th>Rank</th><th>Region</th><th>Efficiency</th><th>Bonus tier</th></tr>
    ${leaderboard
      .slice(0, 8)
      .map(
        (r, i) =>
          `<tr><td>${i + 1}</td><td>${r.name}</td><td>${r.score}/100</td><td>${r.bonus}</td></tr>`
      )
      .join('')}
  </table>

  <h2>IV. Policy advisor transcript (excerpt)</h2>
  ${advisorMessages
    .slice(-4)
    .map(
      (m) =>
        `<p><strong>${m.role === 'ai' ? 'Advisor' : 'Official'}:</strong> ${escapeHtml(m.text).replace(/\n/g, '<br/>')}</p>`
    )
    .join('')}

  <p class="footnote">Generated by Aegis Fiscal Export Bureau. For PDF: File → Print → Save as PDF in your browser.</p>
</body>
</html>`;
}

function escapeHtml(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

export function downloadGazetteHtml(html, filename = 'Aegis_Fiscal_Gazette.html') {
  const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
